// <auto-generated />
namespace MVC_Activity01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBName_Customers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBName_Customers));
        
        string IMigrationMetadata.Id
        {
            get { return "202107280436518_DBName_Customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
